{% set name = "hddm-wfpt" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hddm_wfpt-{{ version }}.tar.gz
  sha256: 258c1bbf552eb5dda10d9c32983572a1e0df1245021304b0a4fea30879b440ff

build:
  skip: true  # [py<=39 or py>314 or py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2.0.0,<3.0.0                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy >=2.0.0,<3.0.0
    - pip
  run:
    - python
    - numpy >=2.0.0,<3.0.0
    - scipy

test:
  imports:
    - hddm_wfpt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lnccbrown/hddm-wfpt
  summary: Cython likelihood functions for the Drift Diffusion Model.
  dev_url: https://github.com/lnccbrown/hddm-wfpt
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - digicosmos86
    - AlexanderFengler
