{% set name = "hddm-wfpt" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hddm_wfpt-{{ version }}.tar.gz
  sha256: b16d318ce47f4691b90e341f29918fd0f7ca0cbce120f794d2e7c8198a40fb6d

build:
  skip: true  # [win or py<=39 or py>=312 or py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - hddm_wfpt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lnccbrown/hddm-wfpt
  summary: Cython likelihood functions for the Drift Diffusion Model.
  dev_url: https://github.com/lnccbrown/hddm-wfpt
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - digicosmos86
    - AlexanderFengler
